### ISSUE TITLE
File-based migrations are not cross-platform (due to path separator differences)

### ISSUE THREAD

**Issue by dougwinsby** [adlio/schema#1]
(v1.1.7) `file.go` uses "path" instead of "path/filepath" for a few path-related operations.

Because Windows uses a **backslash** for the path separator, the file path is not properly interpreted. This results in the migration `ID` to include the entire absolute path instead of just the filename.

Two functions are involved: `MigrationIDFromFilename` and `MigrationsFromDirectoryPath`.

Changing the following appears to correct the problem (although only tested under Windows):

`path.Base()` to `filepath.Base()`
`path.Ext()` to `filepath.Ext()`
`path.Join()` to `filepath.Join()`

**Comment by adlio** [comment]
Awesome. Thank you for the issue report. I have infrequent access to Windows machines, but I should be able to review. Feel free to open a PR. If not, I'll add to my list and evaluated when I get on a Windows machine.

**Comment by dougwinsby** [comment]
I'll send a PR with a test of MigrationIDFromFilename (file_test.go). I got an assignment error in dockertest when running the full package tests. It's probably Windows-specific because the tests ran fine under WSL Ubuntu.

**Comment by adlio** [comment]
This should be fixed in v1.1.8, via commit 0a8aeddf057d3230935855f9506be52e27e611f8. I'm going to leave this issue open, though because we need some better testing to confirm cross-platform support.
