### ISSUE TITLE
Receiver type change breaks use of constructed Migrator

### ISSUE THREAD

**Issue by creachadair** [adlio/schema#13]
Commit a7bc68f4 appears to have changed the methods of the `Migrator` type to accept a pointer rather than a value. The `NewMigrator` constructor, however, still returns a `Migrator` by value, which means that a call like:

```go
err := schema.NewMigrator().Apply(x, y)
```

(which used to work) will now fail because the `Migrator` is in a temporary and the compiler will not desugar the address.

For now I can work around this by rewriting expressions like the above as:

```go
m := schema.NewMigrator()
err := m.Apply(x, y)
```

but I think the value returned by the constructor should have the correct type for use by the methods.

**Comment by adlio** [comment]
Agreed. All my code uses the second form, but I see the argument and will change.

**Comment by adlio** [comment]
The 1.2.3 release tag includes this fix.

**Comment by creachadair** [comment]
Thank you very much for the quick fix!
